window.IKS_TRANSLATIONS = {
  "atharva_1": {
    en: "The Atharvaveda is the fourth and final Veda, named after the ancient sage Atharvan. Unlike the first three Vedas (the Trayi Vidya) which focus primarily on cosmic rituals and priestly duties, the Atharvaveda focuses on the everyday life of the common people. Composed roughly between 1200 and 1000 BCE, it is a fascinating compendium of 730 hymns containing spells, prayers, philosophical reflections, and practical knowledge dealing with disease, agriculture, statecraft, marriage, and family life.",
    hi: "अथर्ववेद चौथा और अंतिम वेद है, जिसका नाम प्राचीन ऋषि अथर्वन के नाम पर रखा गया है। पहले तीन वेदों (त्रयी विद्या) के विपरीत जो मुख्य रूप से ब्रह्मांडीय अनुष्ठानों और पुरोहिती कर्तव्यों पर ध्यान केंद्रित करते हैं, अथर्ववेद आम लोगों के दैनिक जीवन पर ध्यान केंद्रित करता है। लगभग 1200 और 1000 ईसा पूर्व के बीच रचित, यह रोग, कृषि, राजनीति, विवाह और पारिवारिक जीवन से निपटने वाले मंत्रों, प्रार्थनाओं, दार्शनिक विचारों और व्यावहारिक ज्ञान वाले 730 भजनों का एक आकर्षक संग्रह है।"
  },
  "atharva_2": {
    en: "The Atharvaveda is historically significant as the earliest source of Indian medicine. It contains extensive references to human anatomy, descriptions of various diseases (such as fever, jaundice, and snakebite), and the application of medicinal plants (Bheshaja) to cure them. The text clearly identifies that some diseases are caused by microscopic organisms (Krimi) and prescribes herbal remedies alongside protective charms. This practical, observation-based approach to healing laid the foundation for Ayurveda, the traditional Indian system of medicine.",
    hi: "अथर्ववेद भारतीय चिकित्सा के सबसे पुराने स्रोत के रूप में ऐतिहासिक रूप से महत्वपूर्ण है। इसमें मानव शरीर रचना विज्ञान के व्यापक संदर्भ, विभिन्न रोगों (जैसे बुखार, पीलिया और सांप के काटने) का वर्णन और उन्हें ठीक करने के लिए औषधीय पौधों (भेषज) के उपयोग शामिल हैं। यह ग्रंथ स्पष्ट रूप से पहचानता है कि कुछ रोग सूक्ष्म जीवों (कृमि) के कारण होते हैं और सुरक्षात्मक मंत्रों के साथ-साथ हर्बल उपचार निर्धारित करता है। उपचार के इस व्यावहारिक, अवलोकन-आधारित दृष्टिकोण ने पारंपरिक भारतीय चिकित्सा प्रणाली आयुर्वेद की नींव रखी।"
  },
  "atharva_3": {
    en: "Beyond medicine, the Atharvaveda deals extensively with statecraft and governance. It contains hymns on the election of a king by the assembly (Samiti), the duties of a ruler, military strategy, and the maintenance of peace. It also provides insights into ancient Indian agriculture, featuring prayers for abundant crops, protection from pests, and the management of water resources. This makes the Atharvaveda an invaluable sociological document, offering a detailed picture of secular society in ancient India.",
    hi: "चिकित्सा के अलावा, अथर्ववेद राजनीति और शासन के साथ बड़े पैमाने पर संबंधित है। इसमें सभा (समिति) द्वारा एक राजा के चुनाव, एक शासक के कर्तव्यों, सैन्य रणनीति और शांति बनाए रखने पर भजन शामिल हैं। यह प्रचुर मात्रा में फसलों, कीटों से सुरक्षा और जल संसाधनों के प्रबंधन के लिए प्रार्थनाओं की विशेषता के साथ प्राचीन भारतीय कृषि में अंतर्दृष्टि भी प्रदान करता है। यह अथर्ववेद को एक अमूल्य समाजशास्त्रीय दस्तावेज बनाता है, जो प्राचीन भारत में धर्मनिरपेक्ष समाज की विस्तृत तस्वीर पेश करता है।"
  },
  "atharva_4": {
    en: "Philosophically, the Atharvaveda contains profound speculations on the nature of reality. It features the famous Prithvi Sukta (Hymn to the Earth), composed of 63 verses, which is perhaps the world's oldest and most beautiful ecological manifesto. The hymn reveres the Earth as a mother ('Mata Bhumih Putroham Prithivyah' - Earth is my mother, I am her son) and acknowledges her physical features, her diverse peoples, and the need to protect her environment. It prays: 'Whatever I dig from thee, O Earth, may that have quick growth again. O purifier, may we not injure thy vitals or thy heart.'",
    hi: "दार्शनिक रूप से, अथर्ववेद में वास्तविकता की प्रकृति पर गहन अटकलें शामिल हैं। इसमें प्रसिद्ध पृथ्वी सूक्त (पृथ्वी की स्तुति) शामिल है, जो 63 श्लोकों से बना है, जो शायद दुनिया का सबसे पुराना और सबसे सुंदर पारिस्थितिक घोषणापत्र है। यह भजन पृथ्वी को एक माँ के रूप में पूजता है ('माता भूमिः पुत्रोऽहं पृथिव्याः' - पृथ्वी मेरी माता है, मैं उसका पुत्र हूँ) और उसकी भौतिक विशेषताओं, उसके विविध लोगों और उसके पर्यावरण की रक्षा करने की आवश्यकता को स्वीकार करता है। यह प्रार्थना करता है: 'हे पृथ्वी, मैं तुझसे जो कुछ भी खोदूं, वह फिर से जल्दी बढ़े। हे शोधक, हम तेरे मर्म या तेरे हृदय को चोट न पहुँचाएँ।'"
  },
  "atharva_5": {
    en: "The text also includes deeply mystical hymns exploring the concepts of Kala (Time) and Prana (Life-breath) as the ultimate creative principles of the universe. It contains the early roots of philosophical inquiry that would later blossom into the Upanishads. The Mundaka Upanishad, Mandukya Upanishad, and Prashna Upanishad — which contain some of the most advanced metaphysical ideas in Indian philosophy — are all affiliated with the Atharvaveda.",
    hi: "इस ग्रंथ में ब्रह्मांड के अंतिम रचनात्मक सिद्धांतों के रूप में काल (समय) और प्राण (जीवन-श्वास) की अवधारणाओं की खोज करने वाले गहरे रहस्यमय भजन भी शामिल हैं। इसमें दार्शनिक जांच की प्रारंभिक जड़ें शामिल हैं जो बाद में उपनिषदों में विकसित होंगी। मुंडक उपनिषद, मांडूक्य उपनिषद और प्रश्न उपनिषद — जिनमें भारतीय दर्शन के कुछ सबसे उन्नत तत्वमीमांसीय विचार शामिल हैं — सभी अथर्ववेद से संबद्ध हैं।"
  },
  "atharva_6": {
    en: "Today, the Atharvaveda's relevance is strikingly contemporary. Its medical knowledge birthed Ayurveda, which is globally recognized today. Its political hymns foreshadowed democratic principles. Most importantly, its Prithvi Sukta provides a profound spiritual foundation for modern environmentalism, reminding humanity that the Earth is not merely a resource to be exploited, but a sacred, living entity to be nurtured and respected.",
    hi: "आज, अथर्ववेद की प्रासंगिकता आश्चर्यजनक रूप से समकालीन है। इसके चिकित्सा ज्ञान ने आयुर्वेद को जन्म दिया, जिसे आज विश्व स्तर पर मान्यता प्राप्त है। इसके राजनीतिक भजनों ने लोकतांत्रिक सिद्धांतों की भविष्यवाणी की। सबसे महत्वपूर्ण बात, इसका पृथ्वी सूक्त आधुनिक पर्यावरणवाद के लिए एक गहन आध्यात्मिक आधार प्रदान करता है, जो मानवता को याद दिलाता है कि पृथ्वी केवल शोषण करने का संसाधन नहीं है, बल्कि एक पवित्र, जीवित इकाई है जिसका पोषण और सम्मान किया जाना चाहिए।"
  },
  "atharva_7": {
    en: "&copy; 2026 Indian Knowledge Systems. All rights reserved.",
    hi: "&copy; 2026 भारतीय ज्ञान प्रणाली। सर्वाधिकार सुरक्षित।"
  }
};
