window.IKS_TRANSLATIONS = {
  "ayur_1": {
    "en": "Ayurveda — from the Sanskrit words \"Ayur\" (life) and \"Veda\" (knowledge or science) — is the science of life. It is the world's oldest continuously practiced system of medicine, with a documented history spanning more than 5,000 years. Unlike modern allopathic medicine, which primarily focuses on treating disease after it manifests, Ayurveda is fundamentally a system of preventive health — its goal is to maintain and optimize health in the healthy individual rather than merely cure disease in the sick. It approaches the human being as an integrated whole of body, mind, and spirit, and recognizes that all three dimensions must be in balance for genuine health to exist.",
    "hi": "आयुर्वेद — संस्कृत शब्द 'आयुर्' (जीवन) और 'वेद' (ज्ञान या विज्ञान) से — जीवन का विज्ञान है। यह 5,000 से अधिक वर्षों के प्रलेखित इतिहास के साथ, दुनिया की सबसे पुरानी लगातार अभ्यास की जाने वाली चिकित्सा प्रणाली है। आधुनिक एलोपैथिक चिकित्सा के विपरीत, जो मुख्य रूप से बीमारी के प्रकट होने के बाद उसका इलाज करने पर केंद्रित है, आयुर्वेद मूल रूप से निवारक स्वास्थ्य की एक प्रणाली है — इसका लक्ष्य केवल बीमारों की बीमारी को ठीक करने के बजाय स्वस्थ व्यक्ति में स्वास्थ्य को बनाए रखना और अनुकूलित करना है। यह मनुष्य को शरीर, मन और आत्मा के एक एकीकृत रूप में देखता है, और यह मानता है कि वास्तविक स्वास्थ्य के अस्तित्व के लिए तीनों आयामों का संतुलन में होना आवश्यक है।"
  },
  "ayur_2": {
    "en": "The foundational texts of Ayurveda are the Charaka Samhita (focused on internal medicine) and the Sushruta Samhita (focused on surgery and operative medicine), both written in the first millennium BCE. The Sushruta Samhita is particularly remarkable — it describes over 120 surgical instruments and 300 surgical procedures, including cataract surgery, rhinoplasty (reconstruction of the nose), and lithotomy (removal of bladder stones). Sushruta, often called the \"Father of Surgery,\" describes techniques for plastic surgery that would not be developed in the Western world for over two thousand years. Modern plastic surgeons still acknowledge Sushruta's Samhita as the foundational text of their discipline.",
    "hi": "आयुर्वेद के मूलभूत ग्रंथ चरक संहिता (आंतरिक चिकित्सा पर केंद्रित) और सुश्रुत संहिता (सर्जरी और ऑपरेटिव चिकित्सा पर केंद्रित) हैं, जो दोनों पहली सहस्राब्दी ईसा पूर्व में लिखे गए थे। सुश्रुत संहिता विशेष रूप से उल्लेखनीय है — यह मोतियाबिंद सर्जरी, राइनोप्लास्टी (नाक का पुनर्निर्माण), और लिथोटॉमी (मूत्राशय की पथरी को हटाना) सहित 120 से अधिक सर्जिकल उपकरणों और 300 सर्जिकल प्रक्रियाओं का वर्णन करता है। सुश्रुत, जिन्हें अक्सर 'सर्जरी का जनक' कहा जाता है, प्लास्टिक सर्जरी के लिए उन तकनीकों का वर्णन करते हैं जो दो हजार से अधिक वर्षों तक पश्चिमी दुनिया में विकसित नहीं होंगी। आधुनिक प्लास्टिक सर्जन अभी भी सुश्रुत संहिता को अपने अनुशासन के मूलभूत ग्रंथ के रूप में स्वीकार करते हैं।"
  },
  "ayur_3": {
    "en": "At the heart of Ayurvedic physiology is the concept of the three Doshas — Vata, Pitta, and Kapha. These are not merely abstract categories but dynamic biological intelligences that govern every physiological function in the body. Vata, composed of space and air elements, governs all movement — the flow of nerve impulses, the pulsation of the heart, the movement of food through the digestive tract, the flow of breath, and even the movement of thoughts through the mind. When Vata is balanced, there is creativity, vitality, and adaptability; when imbalanced, there is anxiety, irregular function, dryness, and fear. Pitta, composed of fire and water elements, governs all transformation — digestion, metabolism, temperature regulation, and the transformation of sensory impressions into perceptions. When Pitta is balanced, there is sharp intelligence, healthy digestion, and purposeful action; when imbalanced, there is inflammation, anger, and compulsive perfectionism. Kapha, composed of earth and water elements, governs all structure and lubrication — the building of tissues, the maintenance of immunity, and the stability of mind. When balanced, Kapha provides groundedness, compassion, and endurance; when imbalanced, it manifests as lethargy, congestion, and attachment.",
    "hi": "आयुर्वेदिक शरीर विज्ञान के केंद्र में तीन दोषों — वात, पित्त और कफ की अवधारणा है। ये केवल अमूर्त श्रेणियां नहीं हैं, बल्कि गतिशील जैविक बुद्धिमत्ताएं हैं जो शरीर में हर शारीरिक कार्य को नियंत्रित करती हैं। वात, जो अंतरिक्ष और वायु तत्वों से बना है, सभी गतिविधियों को नियंत्रित करता है — तंत्रिका आवेगों का प्रवाह, हृदय की धड़कन, पाचन तंत्र के माध्यम से भोजन की गति, श्वास का प्रवाह, और यहां तक कि मन के माध्यम से विचारों की गति। जब वात संतुलित होता है, तो रचनात्मकता, जीवन शक्ति और अनुकूलनशीलता होती है; असंतुलित होने पर, चिंता, अनियमित कार्य, सूखापन और भय होता है। पित्त, अग्नि और जल तत्वों से बना है, सभी परिवर्तनों को नियंत्रित करता है — पाचन, चयापचय, तापमान विनियमन, और संवेदी छापों को धारणाओं में बदलना। जब पित्त संतुलित होता है, तो तेज बुद्धि, स्वस्थ पाचन और उद्देश्यपूर्ण कार्रवाई होती है; असंतुलित होने पर, सूजन, क्रोध और जुनूनी पूर्णतावाद होता है। कफ, पृथ्वी और जल तत्वों से बना है, सभी संरचना और स्नेहन को नियंत्रित करता है — ऊतकों का निर्माण, प्रतिरक्षा बनाए रखना, और मन की स्थिरता। जब संतुलित होता है, तो कफ जमीनीपन, करुणा और धीरज प्रदान करता है; असंतुलित होने पर, यह सुस्ती, जमाव और लगाव के रूप में प्रकट होता है।"
  },
  "ayur_4": {
    "en": "Every individual has a unique combination of the three Doshas, called their Prakriti (constitutional nature), which is established at conception and remains essentially stable throughout life. Ayurvedic treatment is always individualized — it begins with determining the patient's Prakriti and current imbalances (Vikriti), and then recommending specific foods, herbs, lifestyle practices, and therapies to restore the individual's unique constitutional balance. This recognition that health is not a one-size-fits-all condition — that different people have different physiological natures requiring different approaches — is now being confirmed by the rapidly expanding field of personalized medicine and nutrigenomics.",
    "hi": "प्रत्येक व्यक्ति में तीन दोषों का एक अनूठा संयोजन होता है, जिसे उनकी प्रकृति (संवैधानिक प्रकृति) कहा जाता है, जो गर्भाधान के समय स्थापित होती है और जीवन भर मूल रूप से स्थिर रहती है। आयुर्वेदिक उपचार हमेशा व्यक्तिगत होता है — यह रोगी की प्रकृति और वर्तमान असंतुलन (विकृति) को निर्धारित करने से शुरू होता है, और फिर व्यक्ति के अद्वितीय संवैधानिक संतुलन को बहाल करने के लिए विशिष्ट खाद्य पदार्थों, जड़ी-बूटियों, जीवन शैली प्रथाओं और उपचारों की सिफारिश करता है। यह मान्यता कि स्वास्थ्य कोई एक आकार-सभी के लिए उपयुक्त स्थिति नहीं है — कि अलग-अलग लोगों की अलग-अलग शारीरिक प्रकृति होती है जिनके लिए अलग-अलग दृष्टिकोण की आवश्यकता होती है — अब व्यक्तिगत चिकित्सा और न्यूट्रीजेनोमिक्स के तेजी से बढ़ते क्षेत्र द्वारा पुष्टि की जा रही है।"
  },
  "ayur_5": {
    "en": "Panchakarma — literally \"five actions\" — is Ayurveda's signature detoxification and rejuvenation protocol. The five procedures (Vamana — therapeutic emesis; Virechana — therapeutic purgation; Basti — herbal enemas; Nasya — nasal administration of herbal oils; Raktamokshana — bloodletting or leeching) are designed to systematically eliminate accumulated metabolic waste (Ama) and toxins from different body systems. Panchakarma is always preceded by Purvakarma — preparatory procedures including Snehana (oleation therapy, applying medicated oils internally and externally) and Svedana (steam therapy) — which loosen the toxins from the tissues and bring them into the digestive tract for elimination.",
    "hi": "पंचकर्म — जिसका शाब्दिक अर्थ 'पांच क्रियाएं' है — आयुर्वेद का विशिष्ट विषहरण और कायाकल्प प्रोटोकॉल है। पांच प्रक्रियाएं (वमन — चिकित्सीय उल्टी; विरेचन — चिकित्सीय विरेचन; बस्ती — हर्बल एनीमा; नस्य — हर्बल तेलों का नाक से प्रशासन; रक्तमोक्षण — रक्तपात या जोंक) विभिन्न शरीर प्रणालियों से संचित चयापचय अपशिष्ट (आम) और विषाक्त पदार्थों को व्यवस्थित रूप से खत्म करने के लिए डिज़ाइन की गई हैं। पंचकर्म से हमेशा पहले पूर्वकर्म किया जाता है — प्रारंभिक प्रक्रियाएं जिनमें स्नेहन (ओलिएशन थेरेपी, आंतरिक और बाहरी रूप से औषधीय तेल लगाना) और स्वेदन (स्टीम थेरेपी) शामिल हैं — जो ऊतकों से विषाक्त पदार्थों को ढीला करते हैं और उन्मूलन के लिए उन्हें पाचन तंत्र में लाते हैं।"
  },
  "ayur_6": {
    "en": "Modern research on Panchakarma has produced remarkable findings. Studies at institutions including the Maharishi University of Health and the All India Institute of Medical Sciences have shown that Panchakarma significantly reduces circulating levels of lipid-soluble toxins including PCBs (polychlorinated biphenyls), heavy metals, and pesticide residues — without causing the side effects associated with pharmaceutical chelation therapy. A landmark study published in the journal Alternative Therapies in Health and Medicine found that Panchakarma reduced plasma lipid peroxides (markers of cellular oxidative stress) by 45% and total PCBs by 50% after a single five-day treatment. These findings validate Ayurveda's ancient understanding that specific treatments can mobilize and eliminate stored toxins from body tissues — a mechanism that modern medicine is only beginning to study systematically.",
    "hi": "पंचकर्म पर आधुनिक शोध ने उल्लेखनीय निष्कर्ष प्रस्तुत किए हैं। महर्षि यूनिवर्सिटी ऑफ हेल्थ और ऑल इंडिया इंस्टीट्यूट ऑफ मेडिकल साइंसेज सहित संस्थानों में किए गए अध्ययनों से पता चला है कि पंचकर्म पीसीबी (पॉलीक्लोरीनेटेड बाइफिनाइल), भारी धातुओं और कीटनाशक अवशेषों सहित लिपिड-घुलनशील विषाक्त पदार्थों के परिसंचारी स्तर को काफी कम कर देता है — फार्मास्युटिकल चेलेशन थेरेपी से जुड़े दुष्प्रभावों के बिना। 'ऑल्टरनेटिव थेरेपीज इन हेल्थ एंड मेडिसिन' पत्रिका में प्रकाशित एक ऐतिहासिक अध्ययन में पाया गया कि पंचकर्म ने एक ही पांच-दिवसीय उपचार के बाद प्लाज्मा लिपिड पेरोक्साइड (सेलुलर ऑक्सीडेटिव तनाव के मार्कर) को 45% और कुल पीसीबी को 50% तक कम कर दिया। ये निष्कर्ष आयुर्वेद की प्राचीन समझ को मान्य करते हैं कि विशिष्ट उपचार शरीर के ऊतकों से जमा विषाक्त पदार्थों को सक्रिय और समाप्त कर सकते हैं — एक ऐसा तंत्र जिसका आधुनिक चिकित्सा केवल व्यवस्थित रूप से अध्ययन करना शुरू कर रही है।"
  },
  "ayur_7": {
    "en": "In Ayurveda, food is the most fundamental medicine. The Charaka Samhita states: \"Ahara (food) is the best among all life-sustaining substances... appropriate food in appropriate quantities is the cause of good health.\" Ayurvedic dietary science is extraordinarily sophisticated — it considers not just the nutritional content of food but its qualities (Gunas) such as heavy or light, cold or hot, dry or oily; its taste (Rasa) — sweet, sour, salty, pungent, bitter, or astringent; its post-digestive effect (Vipaka); and its special pharmacological action (Prabhava). Different foods are recommended for different constitutions, different seasons, and different health conditions, and the same food can be either medicine or poison depending on who eats it and in what context.",
    "hi": "आयुर्वेद में, भोजन सबसे मौलिक औषधि है। चरक संहिता में कहा गया है: 'आहार (भोजन) जीवन निर्वाह करने वाले सभी पदार्थों में सर्वश्रेष्ठ है... उचित मात्रा में उचित भोजन अच्छे स्वास्थ्य का कारण है।' आयुर्वेदिक आहार विज्ञान असाधारण रूप से परिष्कृत है — यह न केवल भोजन की पोषण सामग्री पर विचार करता है, बल्कि इसके गुणों (गुण) जैसे कि भारी या हल्का, ठंडा या गर्म, सूखा या तैलीय; इसका स्वाद (रस) — मीठा, खट्टा, नमकीन, तीखा, कड़वा, या कसैला; इसके पाचन के बाद के प्रभाव (विपाक); और इसकी विशेष औषधीय क्रिया (प्रभाव) पर भी विचार करता है। विभिन्न प्रकृति, विभिन्न मौसमों और विभिन्न स्वास्थ्य स्थितियों के लिए अलग-अलग खाद्य पदार्थों की सिफारिश की जाती है, और एक ही भोजन इस बात पर निर्भर करता है कि इसे कौन खाता है और किस संदर्भ में, यह दवा या जहर हो सकता है।"
  },
  "ayur_8": {
    "en": "This multidimensional approach to food is now finding validation in modern nutritional science. The emerging field of nutrigenomics — which studies how dietary factors interact with individual genetic variations to affect health — is discovering that there is no universal optimal diet, that dietary recommendations must be individualized based on genetic profile, microbiome composition, metabolic type, and environmental factors. This is precisely what Ayurveda has been saying for five thousand years. The Ayurvedic principle that eating according to one's constitution and the current season is the most powerful preventive health practice has never been more relevant than it is today, as modern civilization grapples with epidemics of lifestyle diseases that are largely the result of ignoring the basic wisdom encoded in traditional food systems.",
    "hi": "भोजन के प्रति यह बहुआयामी दृष्टिकोण अब आधुनिक पोषण विज्ञान में मान्यता प्राप्त कर रहा है। न्यूट्रीजेनोमिक्स का उभरता हुआ क्षेत्र — जो यह अध्ययन करता है कि आहार कारक स्वास्थ्य को प्रभावित करने के लिए व्यक्तिगत आनुवंशिक विविधताओं के साथ कैसे परस्पर क्रिया करते हैं — यह पता लगा रहा है कि कोई सार्वभौमिक इष्टतम आहार नहीं है, कि आनुवंशिक प्रोफ़ाइल, माइक्रोबायोम संरचना, चयापचय प्रकार और पर्यावरणीय कारकों के आधार पर आहार संबंधी सिफारिशों को व्यक्तिगत किया जाना चाहिए। आयुर्वेद पांच हजार वर्षों से ठीक यही कह रहा है। आयुर्वेदिक सिद्धांत कि किसी के संविधान और वर्तमान मौसम के अनुसार खाना सबसे शक्तिशाली निवारक स्वास्थ्य अभ्यास है, आज से अधिक प्रासंगिक कभी नहीं रहा, क्योंकि आधुनिक सभ्यता जीवन शैली की बीमारियों की महामारी से जूझ रही है जो काफी हद तक पारंपरिक खाद्य प्रणालियों में एन्कोड किए गए बुनियादी ज्ञान की अनदेखी का परिणाम है।"
  },
  "ayur_9": {
    "en": "Ayurveda is now a global phenomenon. The World Health Organization (WHO) has formally recognized Ayurveda as a traditional medicine system and has included Ayurvedic treatments in its Traditional Medicine Strategy. The global Ayurveda market was valued at approximately $9 billion in 2022 and is projected to exceed $15 billion by 2028, driven by growing consumer awareness of the limitations of pharmaceutical medicine and a desire for holistic, preventive health approaches. Yoga retreats, Ayurvedic spas, and wellness centers in Europe, the Americas, and Southeast Asia routinely incorporate Ayurvedic principles and treatments, making Ayurveda one of India's most significant cultural and economic exports.",
    "hi": "आयुर्वेद अब एक वैश्विक घटना है। विश्व स्वास्थ्य संगठन (WHO) ने औपचारिक रूप से आयुर्वेद को एक पारंपरिक चिकित्सा प्रणाली के रूप में मान्यता दी है और अपने पारंपरिक चिकित्सा रणनीति में आयुर्वेदिक उपचारों को शामिल किया है। 2022 में वैश्विक आयुर्वेद बाजार का मूल्य लगभग 9 बिलियन डॉलर था और 2028 तक इसके 15 बिलियन डॉलर से अधिक होने का अनुमान है, जो कि फार्मास्युटिकल दवा की सीमाओं के बारे में बढ़ती उपभोक्ता जागरूकता और समग्र, निवारक स्वास्थ्य दृष्टिकोण की इच्छा से प्रेरित है। यूरोप, अमेरिका और दक्षिण पूर्व एशिया में योग रिट्रीट, आयुर्वेदिक स्पा और वेलनेस सेंटर नियमित रूप से आयुर्वेदिक सिद्धांतों और उपचारों को शामिल करते हैं, जिससे आयुर्वेद भारत के सबसे महत्वपूर्ण सांस्कृतिक और आर्थिक निर्यातों में से एक बन गया है।"
  },
  "ayur_10": {
    "en": "At the same time, Ayurveda is being increasingly integrated with modern biomedicine in what is called Integrative Medicine — an approach that combines the best of both systems. Research institutions in India, the United States, and Europe are conducting rigorous clinical trials on Ayurvedic formulations, and several have shown remarkable efficacy. The COVID-19 pandemic dramatically accelerated interest in Ayurveda — the Indian government's research on formulations like Ashwagandha, Guduchi, and Yashtimadhu as immune modulators generated global attention and contributed to India's relatively resilient response to the pandemic. Ayurveda's moment in the twenty-first century has arrived — and it is a moment shaped by five thousand years of accumulated wisdom.",
    "hi": "उसी समय, आयुर्वेद को आधुनिक बायोमेडिसिन के साथ तेजी से एकीकृत किया जा रहा है जिसे एकीकृत चिकित्सा कहा जाता है — एक ऐसा दृष्टिकोण जो दोनों प्रणालियों के सर्वश्रेष्ठ को जोड़ता है। भारत, संयुक्त राज्य अमेरिका और यूरोप में अनुसंधान संस्थान आयुर्वेदिक योगों पर कठोर नैदानिक परीक्षण कर रहे हैं, और कई ने उल्लेखनीय प्रभावकारिता दिखाई है। COVID-19 महामारी ने आयुर्वेद में रुचि को नाटकीय रूप से तेज कर दिया — प्रतिरक्षा मॉड्यूलेटर के रूप में अश्वगंधा, गिलोय और यष्टिमधु जैसे योगों पर भारत सरकार के शोध ने वैश्विक ध्यान आकर्षित किया और महामारी के प्रति भारत की अपेक्षाकृत लचीली प्रतिक्रिया में योगदान दिया। इक्कीसवीं सदी में आयुर्वेद का क्षण आ गया है — और यह पांच हजार वर्षों के संचित ज्ञान द्वारा आकार दिया गया एक क्षण है।"
  },
  "ayur_11": {
    "en": "&copy; 2026 Indian Knowledge Systems. All rights reserved.",
    "hi": "&copy; 2026 भारतीय ज्ञान प्रणाली। सर्वाधिकार सुरक्षित।"
  }
};
