window.IKS_TRANSLATIONS = {
  rama_origin_1: {
    en: "The Ramayana, known as the Adi Kavya or 'First Poem,' was composed by the sage Valmiki around 500 BCE. It contains 24,000 verses in seven books called Kandas, narrating the journey of Prince Rama of Ayodhya. The word 'Ramayana' means 'the Journey of Rama' and it is not merely a story but a living ethical and spiritual guide that has shaped the lives of billions across Asia for over two millennia.",
    hi: "रामायण, जिसे 'आदि काव्य' अर्थात् प्रथम काव्य कहा जाता है, की रचना महर्षि वाल्मीकि ने लगभग 500 ई.पू. की। इसमें सात काण्डों में 24,000 श्लोक हैं, जो अयोध्या के राजकुमार राम की यात्रा का वर्णन करते हैं। 'रामायण' का अर्थ है 'राम की यात्रा' — यह केवल एक कथा नहीं बल्कि एक जीवंत नैतिक और आध्यात्मिक मार्गदर्शिका है जिसने दो सहस्राब्दियों से अधिक समय तक एशिया में अरबों लोगों के जीवन को आकार दिया है।"
  },
  rama_origin_2: {
    en: "The story of its creation is itself extraordinary. Valmiki, walking by the river Tamasa, witnessed a hunter shoot one of two mating Krauncha birds. Overcome with grief for the surviving bird, he spontaneously uttered a curse in a new rhythmic meter — the Anushtubh. The god Brahma appeared and instructed him to compose the story of Rama in this meter, saying that Rama's life embodies all the dharmic and spiritual wisdom that humanity needs. Valmiki's first pupils were Lava and Kusha — Rama's own sons — who sang the Ramayana before their unknowing father.",
    hi: "इसकी रचना की कथा भी उतनी ही अद्भुत है। तमसा नदी के तट पर भ्रमण करते हुए वाल्मीकि ने एक व्याध को प्रेमरत क्रौंच पक्षियों में से एक को मारते देखा। जीवित पक्षी की पीड़ा से द्रवित होकर उनके मुख से एक श्राप स्वतः ही एक नए छंद में फूट पड़ा — अनुष्टुभ छंद। ब्रह्माजी ने प्रकट होकर उन्हें इसी छंद में राम की कथा रचने का निर्देश दिया। वाल्मीकि के प्रथम शिष्य लव और कुश — राम के अपने पुत्र — थे, जिन्होंने इसे अपने अनजान पिता के सामने गाया।"
  },
  rama_bala_1: {
    en: "The Bala Kanda narrates Rama's divine birth as the seventh Avatar of Vishnu to King Dasharatha of Ayodhya and his queen Kaushalya. Dasharatha performed the Putrakameshti Yajna (a sacred fire ritual for a son), and the gods answered with four divine sons — Rama, Bharata, Lakshmana, and Shatrughna. From childhood, Rama displayed extraordinary qualities of compassion, courage, and dharmic clarity that set him apart as a destined king.",
    hi: "बाल काण्ड में राम के दिव्य जन्म का वर्णन है जो विष्णु के सातवें अवतार के रूप में अयोध्या के राजा दशरथ और रानी कौशल्या के घर हुआ। दशरथ ने पुत्रकामेष्टि यज्ञ किया और देवताओं की कृपा से चार दिव्य पुत्र प्राप्त हुए — राम, भरत, लक्ष्मण और शत्रुघ्न। बचपन से ही राम ने करुणा, साहस और धर्मनिष्ठा के असाधारण गुण प्रदर्शित किए जो उन्हें एक भावी महान राजा के रूप में पहचान दिलाते थे।"
  },
  rama_bala_2: {
    en: "As a young prince, Rama trained under the sage Vishwamitra, who took him to protect his ashram from demons. Rama slew the demoness Tataka, destroyed the demon Maricha's pride, and liberated the sage Ahalya from her curse — all before reaching Mithila. At the swayamvara of King Janaka's daughter Sita, Rama effortlessly lifted and strung the colossal bow of Lord Shiva — a feat no other prince could accomplish — winning Sita's hand and beginning the most celebrated love story in Indian literature.",
    hi: "युवावस्था में राम महर्षि विश्वामित्र के साथ उनके आश्रम की रक्षा के लिए गए। उन्होंने राक्षसी ताड़का का वध किया, मारीच का अहंकार नष्ट किया और अहल्या को श्राप से मुक्त किया — यह सब मिथिला पहुँचने से पहले। राजा जनक की पुत्री सीता के स्वयंवर में राम ने भगवान शिव के विशाल धनुष को सहजता से उठाकर उस पर प्रत्यंचा चढ़ाई — एक ऐसा कार्य जो कोई अन्य राजकुमार नहीं कर सका — और इस प्रकार सीता का हाथ जीतकर भारतीय साहित्य की सर्वाधिक प्रसिद्ध प्रेम कथा का आरंभ किया।"
  },
  rama_ayodhya_1: {
    en: "The Ayodhya Kanda opens with the joyful preparations for Rama's coronation as Crown Prince — only to have everything shattered by the schemes of Kaikeyi, Dasharatha's youngest wife, manipulated by her maid Manthara. Invoking two boons the king had once promised her, Kaikeyi demands that her son Bharata be crowned king and that Rama be exiled to the forest for fourteen years. King Dasharatha, bound by his royal word, collapses in grief — and dies of heartbreak shortly after Rama's departure.",
    hi: "अयोध्या काण्ड राम के युवराज अभिषेक की प्रसन्न तैयारियों से शुरू होता है — परंतु सबकुछ तब बिखर जाता है जब दासी मंथरा के कुप्रभाव में आई कैकेयी षड्यंत्र रचती हैं। राजा से पहले दिए गए दो वरदानों का स्मरण कराते हुए कैकेयी माँगती हैं कि भरत को राजा बनाया जाए और राम को चौदह वर्ष के वनवास पर भेजा जाए। वचनबद्ध राजा दशरथ दुख में ढह जाते हैं और राम के जाने के कुछ समय बाद हृदयविदारक पीड़ा से उनका देहांत हो जाता है।"
  },
  rama_ayodhya_2: {
    en: "Rama, devoted to dharma above all else, accepts the exile without complaint or bitterness. He changes his royal robes for bark and leaves, and prepares to depart. Both Sita — insisting that a wife's place is with her husband — and Lakshmana — unable to live without his elder brother — accompany him to the forest. Bharata, who had been away and returns to find his mother's scheme accomplished and his father dead, refuses the throne and places Rama's sandals upon it, governing as regent until Rama's return — a supreme act of brotherly devotion.",
    hi: "धर्म के प्रति समर्पित राम बिना किसी शिकायत या कटुता के वनवास स्वीकार करते हैं। वे राजसी वस्त्र त्यागकर वल्कल धारण करते हैं। सीता — जो पत्नी का स्थान पति के साथ मानती हैं — और लक्ष्मण — जो बड़े भाई के बिना रह नहीं सकते — दोनों उनके साथ वन को जाते हैं। अनुपस्थित भरत जब लौटते हैं तो माता की चाल और पिता की मृत्यु जानकर सिंहासन अस्वीकार कर देते हैं और राम की खड़ाऊ उस पर रखकर उनके प्रतिनिधि के रूप में राज्य चलाते हैं — भ्रातृभक्ति का यह एक अपूर्व उदाहरण है।"
  },
  rama_aranya_1: {
    en: "In the Aranya Kanda, Rama, Sita and Lakshmana dwell in the Dandaka forest, living as ascetics and protecting sages from demonic attacks. The forest is the space of purification — where Rama's dharma is tested by hardship, encounters with sages and demons, and the steady deepening of his wisdom. He defeats many demons, visits the ashrams of great sages, and receives teachings that prepare him for the trials to come.",
    hi: "अरण्य काण्ड में राम, सीता और लक्ष्मण दंडकारण्य वन में तपस्वी जीवन जीते हैं और ऋषि-मुनियों को राक्षसों से बचाते हैं। वन शुद्धि और परिष्कार का क्षेत्र है — जहाँ कठिनाइयों, ऋषियों और राक्षसों से मुठभेड़ों के माध्यम से राम का धर्म परखा जाता है और उनका ज्ञान गहरा होता है। वे अनेक राक्षसों का संहार करते हैं, महान ऋषियों के आश्रमों में जाते हैं और आने वाली परीक्षाओं के लिए शिक्षाएँ प्राप्त करते हैं।"
  },
  rama_aranya_2: {
    en: "The critical event of this Kanda is Sita's abduction. Surpanakha, the demon sister of Ravana, attempts to seduce Rama and Lakshmana and is repulsed and mutilated. She complains to Ravana, who decides to take revenge by abducting Sita. The demon Maricha takes the form of a golden deer that entrances Sita; she asks Rama to capture it. Rama pursues the deer, and when Lakshmana follows to help him, Ravana — king of Lanka — crosses the protective line (Lakshmana Rekha) and abducts Sita in his flying chariot Pushpaka, carrying her across the sea to Lanka against her will.",
    hi: "इस काण्ड की महत्त्वपूर्ण घटना है सीता का अपहरण। रावण की बहन शूर्पणखा राम और लक्ष्मण को रिझाने की कोशिश करती है और अपमानित होती है। वह रावण से शिकायत करती है जो सीता के अपहरण का षड्यंत्र रचता है। मारीच स्वर्णमृग का रूप धारण कर सीता को मोहित करता है; वे राम से उसे पकड़ने का आग्रह करती हैं। राम मृग के पीछे जाते हैं और जब लक्ष्मण भी जाते हैं, तब रावण लक्ष्मण रेखा पार करके अपने पुष्पक विमान में सीता का अपहरण कर लंका ले जाता है।"
  },
  rama_kishkindha_1: {
    en: "Devastated by Sita's loss, Rama and Lakshmana search the forest desperately. They meet Hanuman — the son of the wind god Vayu — who serves the exiled monkey king Sugriva on the Rishyamuka mountain. Hanuman, recognizing Rama's divine nature, brings him to Sugriva. Rama and Sugriva form a sacred alliance: Rama will slay Vali (the usurper who had stolen Sugriva's throne and wife) and in return Sugriva's monkey army will search for Sita.",
    hi: "सीता की खोज में व्याकुल राम और लक्ष्मण वन में भटकते हैं। वे हनुमान से मिलते हैं — वायु देव के पुत्र — जो ऋष्यमूक पर्वत पर निर्वासित वानरराज सुग्रीव की सेवा में हैं। हनुमान राम की दिव्यता को पहचानकर उन्हें सुग्रीव के पास ले जाते हैं। राम और सुग्रीव के बीच एक पवित्र संधि होती है: राम बाली — जिसने सुग्रीव का राज्य और पत्नी छीन ली थी — का वध करेंगे और बदले में सुग्रीव की वानर सेना सीता की खोज करेगी।"
  },
  rama_kishkindha_2: {
    en: "Rama slays Vali from behind a tree in a disputed act that the epic itself questions, exploring the tension between personal loyalty and cosmic justice. With Sugriva restored to his throne, the massive army of Vanaras (monkeys) and bears is organized for the greatest search operation in mythological history. Search parties are sent in all four directions; it is Hanuman's party heading south who receives from the dying eagle Jatayu the information that Ravana has carried Sita southward. Hanuman is chosen to leap across the ocean to Lanka.",
    hi: "राम एक वृक्ष की आड़ से बाली का वध करते हैं — एक विवादास्पद कार्य जिस पर स्वयं महाकाव्य प्रश्न उठाता है और व्यक्तिगत निष्ठा तथा सार्वभौमिक न्याय के बीच के तनाव को उजागर करता है। सुग्रीव के राज्य पुनः प्राप्त होने के बाद वानरों और भालुओं की विशाल सेना इतिहास के सबसे महान खोज अभियान के लिए संगठित होती है। चारों दिशाओं में दल भेजे जाते हैं; दक्षिण की ओर हनुमान के दल को मरणासन्न गिद्ध जटायु से सूचना मिलती है कि रावण सीता को दक्षिण ले गया है। हनुमान को समुद्र पार लंका जाने के लिए चुना जाता है।"
  },
  rama_sundara_1: {
    en: "The Sundara Kanda — the 'Beautiful Book' — is the most beloved section of the Ramayana and centres entirely on Hanuman's mission to Lanka. When his companions doubt his ability to leap the hundred-league ocean, Hanuman himself momentarily forgets his power. The elder Jambavan reminds him of his divine birth and limitless strength — a metaphor for the soul rediscovering its divine nature through a teacher's guidance. Empowered by this reminder, Hanuman assumes a giant form and in one magnificent leap crosses the ocean, overcomes the sea-demoness Simhika, and lands on the shores of Lanka.",
    hi: "सुंदर काण्ड — 'सुंदर पुस्तक' — रामायण का सर्वाधिक प्रिय खंड है और यह पूर्णतः लंका में हनुमान के मिशन पर केंद्रित है। जब उनके साथी शतयोजन समुद्र पार करने की उनकी क्षमता पर संदेह करते हैं, तो हनुमान स्वयं क्षणभर के लिए अपनी शक्ति भूल जाते हैं। वृद्ध जामवंत उन्हें उनके दिव्य जन्म और असीमित बल का स्मरण कराते हैं — यह आत्मा द्वारा गुरु के मार्गदर्शन से अपनी दिव्यता पुनः पाने का रूपक है। इस स्मरण से शक्तिशाली होकर हनुमान विशालकाय रूप धारण करते हैं और एक छलांग में समुद्र पार करके लंका के तट पर पहुँचते हैं।"
  },
  rama_sundara_2: {
    en: "In Lanka, Hanuman searches through palaces and gardens in his small monkey form, carefully avoiding capture. He finds Sita imprisoned in the Ashoka grove under the guard of demon women, steadfastly refusing Ravana's proposals and sustained only by her devotion to Rama. Hanuman reveals himself, gives her Rama's signet ring as proof, and delivers Rama's message of hope and imminent rescue. Before leaving, Hanuman allows himself to be captured, brought before Ravana's court, and punished by having his tail set on fire — whereupon he uses his burning tail to set Lanka ablaze, then returns triumphantly across the ocean with the news that Sita is alive.",
    hi: "लंका में हनुमान अपने छोटे वानर रूप में महलों और वाटिकाओं में खोज करते हैं। उन्हें अशोक वाटिका में राक्षस स्त्रियों के पहरे में बंदी सीता मिलती हैं जो रावण के प्रस्तावों को दृढ़ता से अस्वीकार करती हैं और केवल राम की भक्ति से जीवित हैं। हनुमान अपना परिचय देते हैं, राम की अंगूठी साक्ष्य के रूप में देते हैं और आशा तथा शीघ्र मुक्ति का संदेश सुनाते हैं। जाने से पहले हनुमान जानबूझकर पकड़े जाते हैं, रावण की सभा में लाए जाते हैं और उनकी पूँछ में आग लगाई जाती है — जिससे वे जलती पूँछ से पूरी लंका जला देते हैं और फिर विजयपूर्वक समुद्र पार कर सीता के जीवित होने की खुशखबरी लाते हैं।"
  },
  rama_yuddha_1: {
    en: "The Yuddha Kanda narrates the climactic war. Nala and Nila, gifted monkey builders, construct a miraculous bridge (Rama Setu) of floating stones across the ocean to Lanka — each stone inscribed with Rama's name. Crossing this bridge, the vast army of Vanaras and bears reaches Lanka and besieges the city. The battle that follows is one of the most dramatic in world literature — armies clash, divine weapons are unleashed, great heroes fall on both sides. Ravana's noble brother Vibhishana, horrified by the injustice of Sita's abduction, defects to Rama's side and becomes a key advisor.",
    hi: "युद्ध काण्ड में अंतिम महायुद्ध का वर्णन है। कुशल वानर निर्माता नल और नील समुद्र के पार लंका तक एक चमत्कारी पुल — राम सेतु — का निर्माण करते हैं, जिसके प्रत्येक पत्थर पर राम का नाम अंकित है। इस सेतु को पार करके वानर और भालुओं की विशाल सेना लंका पहुँचती है। जो युद्ध होता है वह विश्व साहित्य का एक सर्वाधिक नाटकीय युद्ध है — सेनाएँ भिड़ती हैं, दिव्यास्त्र छूटते हैं, दोनों पक्षों के महावीर वीरगति पाते हैं। रावण के उदार भाई विभीषण, सीता हरण की अनीति से क्षुब्ध होकर, राम की शरण में आते हैं और महत्त्वपूर्ण सलाहकार बनते हैं।"
  },
  rama_yuddha_2: {
    en: "In the final confrontation, Rama and Ravana engage in a titanic single combat. Ravana's heads are cut off but regenerate until the sage Agastya teaches Rama the Aditya Hridayam — a hymn to the Sun god — and gives him the divine Brahmastra. With this supreme weapon, Rama finally slays Ravana. Sita passes the Agni Pariksha (trial by fire) to prove her purity; the fire god Agni returns her unharmed, and the gods celebrate from the heavens. Rama's father Dasharatha descends from heaven to bless his son. The Pushpaka Vimana carries Rama, Sita, and all their allies back to Ayodhya, where the people light oil lamps to welcome their king — the origin of the festival of Diwali.",
    hi: "अंतिम संग्राम में राम और रावण के बीच भीषण एकल युद्ध होता है। रावण के सिर कटते हैं पर वापस उग आते हैं, जब तक महर्षि अगस्त्य राम को आदित्य हृदयम — सूर्यदेव का स्तोत्र — सिखाते हैं और दिव्य ब्रह्मास्त्र देते हैं। इस परम अस्त्र से राम अंततः रावण का वध करते हैं। सीता अग्नि परीक्षा देती हैं; अग्निदेव उन्हें अक्षत लौटाते हैं और देवगण स्वर्ग से उत्सव मनाते हैं। दशरथ स्वर्ग से उतरकर पुत्र को आशीर्वाद देते हैं। पुष्पक विमान राम, सीता और सबको अयोध्या ले जाता है जहाँ प्रजा दीपक जलाकर अपने राजा का स्वागत करती है — इसी से दीपावली पर्व का जन्म हुआ।"
  },
  rama_uttara_1: {
    en: "The Uttara Kanda narrates Rama's coronation and his establishment of Rama Rajya — a golden age of perfect justice, prosperity, and dharma in which no subject suffers, every person fulfils their purpose, and the king rules as the servant of his people. This ideal of Ramarajya became the supreme standard of good governance in Indian civilization — a vision of the state not as an instrument of power but as a mechanism of collective dharmic flourishing. Mahatma Gandhi made Ramarajya the central vision of his independence movement.",
    hi: "उत्तर काण्ड में राम के राज्याभिषेक और रामराज्य की स्थापना का वर्णन है — एक स्वर्णयुग जिसमें कोई प्रजाजन कष्ट नहीं पाता, प्रत्येक व्यक्ति अपना धर्म निभाता है और राजा प्रजा का सेवक बनकर शासन करता है। रामराज्य का यह आदर्श भारतीय सभ्यता में सुशासन की सर्वोच्च कसौटी बन गया — राज्य की ऐसी दृष्टि जो शक्ति का नहीं बल्कि सामूहिक धार्मिक उत्कर्ष का माध्यम है। महात्मा गांधी ने रामराज्य को अपने स्वतंत्रता आंदोलन की केंद्रीय दृष्टि बनाया।"
  },
  rama_uttara_2: {
    en: "In the later and more controversial chapters, a washerman publicly questions Sita's purity after her time in Lanka. Rama, torn between his love for Sita and his duty as a king to uphold public opinion, sends the pregnant Sita to the forest — where she is sheltered by Valmiki and gives birth to twin sons Lava and Kusha. Years later, Lava and Kusha sing the Ramayana before their unknowing father at a great sacrifice; Rama recognizes them as his sons but Sita, summoned to prove her purity again before the public, calls upon the Earth — her divine mother — to receive her back, and the earth opens and takes her. Rama, heartbroken, eventually ascends to his divine abode in the Sarayu river.",
    hi: "बाद के अध्यायों में एक धोबी सीता की पवित्रता पर सार्वजनिक रूप से प्रश्न उठाता है। राम सीता के प्रति अपने प्रेम और राजा के रूप में लोकमत की रक्षा के कर्तव्य के बीच द्वंद्व में फँसकर गर्भवती सीता को वन भेज देते हैं — जहाँ वाल्मीकि उन्हें आश्रय देते हैं और वे लव-कुश को जन्म देती हैं। वर्षों बाद एक महायज्ञ में लव-कुश राम के सामने रामायण गाते हैं; राम उन्हें अपना पुत्र पहचानते हैं पर जब सीता को पुनः लोकसभा के समक्ष पवित्रता प्रमाणित करने को कहा जाता है, तब वे धरती माता का आह्वान करती हैं और पृथ्वी फट जाती है और उन्हें अपने में समा लेती है। टूटे हृदय से राम अंततः सरयू नदी में अपने दिव्य धाम को प्रस्थान करते हैं।"
  }
};
