window.IKS_TRANSLATIONS = {
  "rig_1": {
    en: "The Rigveda is the oldest of the four Vedas and one of the oldest extant texts of any Indo-European language, composed approximately between 1500 and 1200 BCE. It is a magnificent collection of 10,552 hymns (known as Richas) organized into ten books called Mandalas. These Mandalas were composed by different seer-families (Rishis) over generations and then compiled together to form a unified sacred corpus. The word \"Rig\" derives from the Sanskrit \"Rc,\" meaning praise or verse, and the Rigveda is fundamentally a book of praise — of the cosmos, of natural forces, and of the divine principles that govern existence.",
    hi: "ऋग्वेद चारों वेदों में सबसे पुराना है और किसी भी इंडो-यूरोपीय भाषा के सबसे पुराने उपलब्ध ग्रंथों में से एक है, जिसकी रचना लगभग 1500 से 1200 ईसा पूर्व के बीच हुई थी। यह 10,552 सूक्तों (जिन्हें ऋचाएँ कहा जाता है) का एक शानदार संग्रह है, जिन्हें दस पुस्तकों (मण्डलों) में व्यवस्थित किया गया है। इन मण्डलों की रचना पीढ़ियों तक विभिन्न ऋषि परिवारों द्वारा की गई और फिर इन्हें एक एकीकृत पवित्र ग्रंथ बनाने के लिए संकलित किया गया। 'ऋग्' शब्द संस्कृत के 'ऋच्' से बना है, जिसका अर्थ है स्तुति या श्लोक, और ऋग्वेद मूल रूप से स्तुति की पुस्तक है — ब्रह्मांड, प्राकृतिक शक्तियों और अस्तित्व को नियंत्रित करने वाले दिव्य सिद्धांतों की।"
  },
  "rig_2": {
    en: "The Rigveda's ten Mandalas vary in size. Mandalas 2 through 7, known as the \"Family Books,\" are the oldest core and are associated with particular Rishi lineages such as the Gritsamada, Vishvamitra, Vamadeva, Atri, Bharadvaja, and Vasishtha families. Mandalas 1, 8, 9, and 10 were added later. The ninth Mandala, the Soma Mandala, is entirely devoted to hymns to Soma — the sacred ritual plant whose juice formed the central offering in Vedic sacrifices. This organized structure tells us that the Vedic tradition was a living, growing intellectual tradition, not a static text.",
    hi: "ऋग्वेद के दस मण्डलों का आकार भिन्न-भिन्न है। मण्डल 2 से 7 तक, जिन्हें 'पारिवारिक पुस्तकें' कहा जाता है, सबसे पुराना मूल भाग हैं और गृत्समद, विश्वामित्र, वामदेव, अत्रि, भारद्वाज और वशिष्ठ जैसे विशिष्ट ऋषि वंशों से जुड़े हैं। मण्डल 1, 8, 9 और 10 बाद में जोड़े गए। नौवां मण्डल, सोम मण्डल, पूरी तरह से सोम को समर्पित सूक्तों का है — वह पवित्र अनुष्ठानिक पौधा जिसका रस वैदिक यज्ञों में मुख्य आहुति था। यह सुव्यवस्थित संरचना हमें बताती है कि वैदिक परंपरा एक जीवंत, विकासशील बौद्धिक परंपरा थी, न कि कोई स्थिर ग्रंथ।"
  },
  "rig_3": {
    en: "The Rigveda addresses over thirty major deities, each representing a force or principle in the natural and cosmic order. Agni, the god of fire, is addressed in more hymns than any other deity. He is the divine priest, the messenger between humans and gods, and the embodiment of the sacred flame that transforms offerings into the cosmic cycle of giving and receiving. Indra, the warrior king of the gods, is praised for his cosmic battles against the demon Vritra — a mythological metaphor for the forces of obstruction, drought, and chaos being overcome by divine energy. Varuna, the god of cosmic law and waters, upholds Rita — the principle of truth and cosmic order — and represents an early Indian conception of moral governance.",
    hi: "ऋग्वेद तीस से अधिक प्रमुख देवताओं को संबोधित करता है, जिनमें से प्रत्येक प्राकृतिक और ब्रह्मांडीय व्यवस्था में एक शक्ति या सिद्धांत का प्रतिनिधित्व करता है। अग्नि, अग्नि के देवता, को किसी भी अन्य देवता की तुलना में अधिक सूक्तों में संबोधित किया गया है। वे दिव्य पुरोहित हैं, मनुष्यों और देवताओं के बीच संदेशवाहक हैं, और उस पवित्र ज्वाला के अवतार हैं जो आहुतियों को देने और प्राप्त करने के ब्रह्मांडीय चक्र में बदल देती है। देवताओं के योद्धा राजा इंद्र की स्तुति राक्षस वृत्र के खिलाफ उनके ब्रह्मांडीय युद्धों के लिए की गई है — जो कि बाधा, सूखे और अराजकता की शक्तियों पर दिव्य ऊर्जा द्वारा विजय प्राप्त करने का एक पौराणिक रूपक है। वरुण, ब्रह्मांडीय कानून और जल के देवता, ऋत — सत्य और ब्रह्मांडीय व्यवस्था के सिद्धांत — को बनाए रखते हैं और नैतिक शासन की प्रारंभिक भारतीय अवधारणा का प्रतिनिधित्व करते हैं।"
  },
  "rig_4": {
    en: "Surya (the Sun), Ushas (Dawn), Vayu (Wind), and the Ashvins (divine twin physicians) are among the many deities celebrated. What is remarkable about the Rigvedic conception of divinity is its philosophical sophistication: many hymns suggest that all divine names and forms ultimately point to a single ultimate reality. This is expressed most powerfully in the Purusha Sukta (10.90), which describes the cosmic being from whose sacrifice the entire universe was created — an early articulation of the concept of Brahman, the universal consciousness.",
    hi: "सूर्य, उषा (भोर), वायु और अश्विनी कुमार (दिव्य जुड़वां चिकित्सक) स्तुति किए गए कई देवताओं में से हैं। दिव्यता की ऋग्वैदिक अवधारणा के बारे में जो उल्लेखनीय है वह इसकी दार्शनिक परिष्कृतता है: कई सूक्त बताते हैं कि सभी दिव्य नाम और रूप अंततः एक ही परम वास्तविकता की ओर इशारा करते हैं। इसे पुरुष सूक्त (10.90) में सबसे शक्तिशाली रूप से व्यक्त किया गया है, जो उस ब्रह्मांडीय पुरुष का वर्णन करता है जिसके बलिदान से पूरे ब्रह्मांड का निर्माण हुआ था — ब्रह्मांडीय चेतना, ब्रह्म की अवधारणा की एक प्रारंभिक अभिव्यक्ति।"
  },
  "rig_5": {
    en: "Among all its hymns, the Gayatri Mantra — found in Mandala 3, verse 62.10 — stands as the most universally revered. \"Om Bhur Bhuva Swaha, Tat Savitur Varenyam, Bhargo Devasya Dhimahi, Dhiyo Yo Nah Prachodayat\" — this mantra is a prayer to the divine light of the Sun (Savitur) to illuminate the mind and intellect. For three thousand years, this mantra has been chanted at sunrise and sunset by millions across India. Modern phonetic research has shown that the specific vibrational frequencies of this mantra activate areas of the brain associated with alertness and cognitive clarity — a validation of ancient intuition through the language of modern neuroscience.",
    hi: "इसके सभी सूक्तों में, गायत्री मंत्र — जो मण्डल 3, श्लोक 62.10 में पाया जाता है — सबसे सार्वभौमिक रूप से पूजनीय है। 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्' — यह मंत्र मन और बुद्धि को रोशन करने के लिए सूर्य (सविता) के दिव्य प्रकाश से की गई एक प्रार्थना है। तीन हजार वर्षों से, इस मंत्र का भारत भर में लाखों लोगों द्वारा सूर्योदय और सूर्यास्त के समय जाप किया जाता रहा है। आधुनिक ध्वन्यात्मक अनुसंधान से पता चला है कि इस मंत्र की विशिष्ट कंपन आवृत्तियाँ सतर्कता और संज्ञानात्मक स्पष्टता से जुड़े मस्तिष्क के क्षेत्रों को सक्रिय करती हैं — जो आधुनिक तंत्रिका विज्ञान की भाषा के माध्यम से प्राचीन अंतर्ज्ञान का सत्यापन है।"
  },
  "rig_6": {
    en: "Perhaps the most philosophically remarkable hymn is the Nasadiya Sukta (10.129), the Hymn of Creation. In just seven verses, it asks: \"Who really knows? Who will here proclaim it? Whence was it produced? Whence is this creation? Perhaps it formed itself, or perhaps it did not — the one who looks down on it, in the highest heaven, only he knows — or perhaps he does not know.\" This is not religious dogma — it is a genuinely scientific questioning of the origins of the universe, maintaining intellectual honesty about the limits of knowledge. Cosmologists and philosophers of science today marvel at the modernity of this enquiry, composed more than three millennia ago.",
    hi: "शायद सबसे दार्शनिक रूप से उल्लेखनीय सूक्त नासदीय सूक्त (10.129) है, जिसे सृष्टि का सूक्त कहा जाता है। केवल सात श्लोकों में, यह पूछता है: 'कौन वास्तव में जानता है? यहाँ कौन इसकी घोषणा करेगा? यह कहाँ से उत्पन्न हुआ? यह सृष्टि कहाँ से आई? शायद यह स्वयं बन गई, या शायद नहीं — जो उच्चतम स्वर्ग में बैठकर इसे नीचे देखता है, केवल वही जानता है — या शायद वह भी नहीं जानता।' यह कोई धार्मिक हठधर्मिता नहीं है — यह ब्रह्मांड की उत्पत्ति के बारे में एक वास्तविक वैज्ञानिक प्रश्न है, जो ज्ञान की सीमाओं के बारे में बौद्धिक ईमानदारी बनाए रखता है। आज के ब्रह्मांड विज्ञानी और विज्ञान के दार्शनिक तीन सहस्राब्दी से अधिक समय पहले रचित इस जांच की आधुनिकता पर आश्चर्य करते हैं।"
  },
  "rig_7": {
    en: "The Rigveda is not merely a religious text — it is an encyclopaedia of early human knowledge. Its hymns contain detailed observations of the night sky, recording positions of stars, solstices, and equinoxes that archaeoastronomers have used to independently confirm their antiquity. The Rigveda also contains references to medicinal plants used in healing — references so specific that Ayurvedic scholars trace the roots of Indian herbal medicine to these very verses. The hymns to rivers (Sapta Sindhu) contain descriptions of the geography of ancient India that provide historians with evidence of the civilization's extent.",
    hi: "ऋग्वेद केवल एक धार्मिक ग्रंथ नहीं है — यह प्रारंभिक मानव ज्ञान का एक विश्वकोश है। इसके सूक्तों में रात के आकाश के विस्तृत अवलोकन शामिल हैं, तारों की स्थिति, संक्रांति और विषुव की रिकॉर्डिंग जिनका उपयोग पुरा-खगोलशास्त्रियों ने स्वतंत्र रूप से उनकी प्राचीनता की पुष्टि करने के लिए किया है। ऋग्वेद में उपचार में प्रयुक्त औषधीय पौधों के संदर्भ भी शामिल हैं — इतने विशिष्ट संदर्भ कि आयुर्वेदिक विद्वान भारतीय हर्बल चिकित्सा की जड़ों को इन्हीं श्लोकों में खोजते हैं। नदियों (सप्त सिंधु) के सूक्तों में प्राचीन भारत के भूगोल का विवरण है जो इतिहासकारों को सभ्यता के विस्तार का प्रमाण प्रदान करता है।"
  },
  "rig_8": {
    en: "At the heart of Rigvedic thought is the concept of Rita — the cosmic order, truth, and righteousness that governs both the natural world and human conduct. Rita is maintained by Varuna and Mitra, the gods of moral governance. When humans act in accordance with Rita — speaking truth, performing their duties, living ethically — they sustain the cosmic harmony. When they violate Rita, they disturb the universal order. This idea is the direct forerunner of Dharma, the ethical framework that underpins all of Indian philosophy, law, and governance to this day. The Rigvedic hymn \"Sangachadhvam samvadadhvam\" — \"Come together, speak together, let our minds be as one\" — is perhaps the world's oldest articulation of democratic, consensual governance.",
    hi: "ऋग्वैदिक विचार के केंद्र में ऋत की अवधारणा है — ब्रह्मांडीय व्यवस्था, सत्य और धार्मिकता जो प्राकृतिक दुनिया और मानव आचरण दोनों को नियंत्रित करती है। वरुण और मित्र, नैतिक शासन के देवता, ऋत को बनाए रखते हैं। जब मनुष्य ऋत के अनुसार कार्य करते हैं — सत्य बोलना, अपने कर्तव्यों का पालन करना, नैतिक रूप से जीना — तो वे ब्रह्मांडीय सामंजस्य को बनाए रखते हैं। जब वे ऋत का उल्लंघन करते हैं, तो वे सार्वभौमिक व्यवस्था को भंग करते हैं। यह विचार धर्म का प्रत्यक्ष अग्रदूत है, वह नैतिक ढांचा जो आज तक सभी भारतीय दर्शन, कानून और शासन का आधार है। ऋग्वैदिक सूक्त 'संगच्छध्वं संवदध्वं' — 'एक साथ आओ, एक साथ बोलो, हमारे मन एक हों' — शायद लोकतांत्रिक, सर्वसम्मति वाले शासन की दुनिया की सबसे पुरानी अभिव्यक्ति है।"
  },
  "rig_9": {
    en: "In 2008, UNESCO inscribed the tradition of Vedic chanting on its list of Intangible Cultural Heritages of Humanity, recognising the Rigveda's oral tradition — preserved with remarkable accuracy for over three thousand years through a sophisticated system of chanting, counter-chanting, and verification — as one of humanity's greatest intellectual achievements. The tradition of memorising the entire Rigveda through Pathashalas (Vedic schools) continues to this day in India, with young scholars preserving every syllable of this 10,000-verse text through dedicated years of study.",
    hi: "2008 में, यूनेस्को ने वैदिक मंत्रोच्चारण की परंपरा को मानवता की अमूर्त सांस्कृतिक विरासत की अपनी सूची में अंकित किया, ऋग्वेद की मौखिक परंपरा — जिसे तीन हजार से अधिक वर्षों तक मंत्रोच्चारण, प्रति-मंत्रोच्चारण और सत्यापन की एक परिष्कृत प्रणाली के माध्यम से उल्लेखनीय सटीकता के साथ संरक्षित किया गया है — को मानवता की सबसे बड़ी बौद्धिक उपलब्धियों में से एक के रूप में मान्यता दी। पाठशालाओं (वैदिक विद्यालयों) के माध्यम से संपूर्ण ऋग्वेद को याद करने की परंपरा आज भी भारत में जारी है, जहाँ युवा विद्वान अध्ययन के समर्पित वर्षों के माध्यम से इस 10,000 श्लोक वाले ग्रंथ के प्रत्येक शब्दांश को संरक्षित कर रहे हैं।"
  },
  "rig_10": {
    en: "For contemporary society, the Rigveda offers profound insights. Its ecological hymns — treating rivers, forests, and the Earth as sacred — resonate deeply with modern environmentalism. Its philosophical openness — acknowledging uncertainty about ultimate truths — resonates with the scientific method. Its social ethics — unity, consensus, and truth — remain the foundational values of any just society. The Rigveda reminds us that the deepest questions humanity faces today — about the origins of the universe, the nature of consciousness, the ethics of community life — were first asked, with extraordinary sophistication, by our ancient ancestors on the banks of the Sarasvati river more than three thousand years ago.",
    hi: "समकालीन समाज के लिए, ऋग्वेद गहन अंतर्दृष्टि प्रदान करता है। इसके पारिस्थितिक सूक्त — नदियों, जंगलों और पृथ्वी को पवित्र मानते हुए — आधुनिक पर्यावरणवाद के साथ गहराई से प्रतिध्वनित होते हैं। इसका दार्शनिक खुलापन — परम सत्यों के बारे में अनिश्चितता को स्वीकार करना — वैज्ञानिक पद्धति के साथ प्रतिध्वनित होता है। इसकी सामाजिक नैतिकता — एकता, सर्वसम्मति और सत्य — किसी भी न्यायपूर्ण समाज के मूलभूत मूल्य बने हुए हैं। ऋग्वेद हमें याद दिलाता है कि आज मानवता जिन सबसे गहरे सवालों का सामना कर रही है — ब्रह्मांड की उत्पत्ति, चेतना की प्रकृति, सामुदायिक जीवन की नैतिकता के बारे में — वे सबसे पहले, असाधारण परिष्कृतता के साथ, हमारे प्राचीन पूर्वजों द्वारा तीन हजार से अधिक वर्ष पहले सरस्वती नदी के तट पर पूछे गए थे।"
  },
  "rig_11": {
    en: "&copy; 2026 Indian Knowledge Systems. All rights reserved.",
    hi: "&copy; 2026 भारतीय ज्ञान प्रणाली। सर्वाधिकार सुरक्षित।"
  }
};
