window.IKS_TRANSLATIONS = {
  "sama_1": {
    en: "The Samaveda is the Veda of melodies and chants. While the Rigveda is meant to be recited, the Samaveda is meant to be sung. It is essentially an anthology of Rigvedic hymns set to specific musical notes, making it the foundational text of Indian classical music. The word 'Saman' translates to melody, and the text provides the structural basis for the complex ragas that continue to define the musical heritage of the Indian subcontinent.",
    hi: "सामवेद धुन और भजनों का वेद है। जहाँ ऋग्वेद का पाठ किया जाता है, वहीं सामवेद को गाया जाता है। यह मूल रूप से विशिष्ट संगीत स्वरों पर आधारित ऋग्वैदिक सूक्तों का एक संकलन है, जो इसे भारतीय शास्त्रीय संगीत का मूलभूत ग्रंथ बनाता है। 'सामन' शब्द का अर्थ है धुन, और यह ग्रंथ उन जटिल रागों के लिए संरचनात्मक आधार प्रदान करता है जो आज भी भारतीय उपमहाद्वीप की संगीत विरासत को परिभाषित करते हैं।"
  },
  "sama_2": {
    en: "Composed approximately between 1200 and 1000 BCE, the Samaveda contains 1,549 verses, of which all but 75 are drawn directly from the Rigveda. However, the true genius of the Samaveda lies not in its textual content but in its musical application. The text was chanted by a special class of priests called the Udgatris during the Soma sacrifices. By setting words to musical meter, the Samaveda elevated ritual recitation into an aesthetic and spiritual experience.",
    hi: "लगभग 1200 और 1000 ईसा पूर्व के बीच रचित, सामवेद में 1,549 श्लोक हैं, जिनमें से 75 को छोड़कर बाकी सभी सीधे ऋग्वेद से लिए गए हैं। हालाँकि, सामवेद की वास्तविक प्रतिभा इसके पाठ्य सामग्री में नहीं बल्कि इसके संगीत अनुप्रयोग में निहित है। सोम यज्ञों के दौरान 'उद्गाता' नामक पुजारियों के एक विशेष वर्ग द्वारा इस ग्रंथ का जाप किया जाता था। शब्दों को संगीत मीटर में सेट करके, सामवेद ने अनुष्ठानिक पाठ को एक सौंदर्य और आध्यात्मिक अनुभव में बदल दिया।"
  },
  "sama_3": {
    en: "The Samaveda introduced the concept of the seven basic musical notes (Swara): Sa, Re, Ga, Ma, Pa, Dha, Ni — which correspond roughly to the Do, Re, Mi, Fa, Sol, La, Ti of Western classical music. This systematization of sound was a monumental scientific achievement. The Samavedic chants were composed to follow the natural inflections of the human voice, with precise instructions on pitch, rhythm, and duration. This rigorous methodology ensured that the chants could be transmitted orally across millennia without losing their original acoustic properties.",
    hi: "सामवेद ने सात मूल संगीत स्वरों (स्वर) की अवधारणा प्रस्तुत की: सा, रे, ग, म, प, ध, नि — जो मोटे तौर पर पश्चिमी शास्त्रीय संगीत के डो, रे, मी, फा, सोल, ला, टी के अनुरूप हैं। ध्वनि का यह व्यवस्थितकरण एक महान वैज्ञानिक उपलब्धि थी। सामवेदी भजनों को मानव आवाज के प्राकृतिक झुकाव का पालन करने के लिए रचित किया गया था, जिसमें पिच, ताल और अवधि पर सटीक निर्देश दिए गए थे। इस कठोर कार्यप्रणाली ने सुनिश्चित किया कि भजनों को उनके मूल ध्वनिक गुणों को खोए बिना सहस्राब्दियों तक मौखिक रूप से प्रेषित किया जा सके।"
  },
  "sama_4": {
    en: "The central ritual associated with the Samaveda is the Soma sacrifice. Soma was both a plant and a deity, representing the divine elixir of inspiration and immortality. The pressing of the Soma plant was accompanied by the chanting of Samans. This combination of the physical offering of Soma and the acoustic offering of the Saman was believed to connect the human realm directly to the divine. The music was not merely entertainment; it was a form of active meditation designed to alter consciousness and bring the mind into harmony with the cosmic order.",
    hi: "सामवेद से जुड़ा मुख्य अनुष्ठान सोम यज्ञ है। सोम एक पौधा और एक देवता दोनों था, जो प्रेरणा और अमरता के दिव्य अमृत का प्रतिनिधित्व करता था। सोम के पौधे को निचोड़ने के साथ-साथ सामन का जाप किया जाता था। सोम की भौतिक आहुति और सामन की ध्वनिक आहुति के इस संयोजन को मानव क्षेत्र को सीधे परमात्मा से जोड़ने वाला माना जाता था। संगीत केवल मनोरंजन नहीं था; यह सक्रिय ध्यान का एक रूप था जिसे चेतना को बदलने और मन को ब्रह्मांडीय व्यवस्था के साथ सामंजस्य में लाने के लिए डिज़ाइन किया गया था।"
  },
  "sama_5": {
    en: "Philosophically, the Samaveda emphasizes the power of sound (Nada) as the fundamental creative force of the universe. The Chandogya Upanishad, one of the oldest and most significant Upanishads, is embedded within the Samavedic tradition. It famously declares the great Mahavakya (profound statement) 'Tat Tvam Asi' — 'Thou Art That' — teaching that the individual soul (Atman) and the universal reality (Brahman) are ultimately one. This spiritual teaching is delivered not as a dry intellectual concept, but as a truth to be felt and realized through the medium of sacred sound.",
    hi: "दार्शनिक रूप से, सामवेद ध्वनि (नाद) की शक्ति पर जोर देता है जो ब्रह्मांड की मौलिक रचनात्मक शक्ति है। छांदोग्य उपनिषद, जो सबसे पुराने और सबसे महत्वपूर्ण उपनिषदों में से एक है, सामवेदी परंपरा के भीतर सन्निहित है। यह प्रसिद्ध रूप से महान महावाक्य 'तत् त्वम् असि' — 'तुम वही हो' — की घोषणा करता है, जो यह सिखाता है कि व्यक्तिगत आत्मा (आत्मा) और सार्वभौमिक वास्तविकता (ब्रह्म) अंततः एक हैं। यह आध्यात्मिक शिक्षा एक शुष्क बौद्धिक अवधारणा के रूप में नहीं, बल्कि पवित्र ध्वनि के माध्यम से महसूस की जाने वाली और महसूस की जाने वाली सच्चाई के रूप में दी जाती है।"
  },
  "sama_6": {
    en: "Today, the Samavedic tradition is recognized as the mother of all Indian musical traditions — both Hindustani (Northern) and Carnatic (Southern). The deep connection between music, emotion, and spirituality that defines Indian music traces its lineage directly back to these ancient chants. In a world increasingly recognizing the therapeutic value of sound and music therapy, the Samaveda stands as a three-thousand-year-old testament to the profound impact of organized sound on human psychology and spiritual well-being.",
    hi: "आज, सामवेदी परंपरा को सभी भारतीय संगीत परंपराओं — हिंदुस्तानी (उत्तरी) और कर्नाटक (दक्षिणी) दोनों — की जननी के रूप में मान्यता प्राप्त है। संगीत, भावना और आध्यात्मिकता के बीच गहरा संबंध जो भारतीय संगीत को परिभाषित करता है, वह सीधे इन प्राचीन भजनों में अपना वंश खोजता है। एक ऐसी दुनिया में जो ध्वनि और संगीत चिकित्सा के चिकित्सीय मूल्य को तेजी से पहचान रही है, सामवेद मानव मनोविज्ञान और आध्यात्मिक कल्याण पर संगठित ध्वनि के गहरे प्रभाव के तीन हजार साल पुराने वसीयतनामे के रूप में खड़ा है।"
  },
  "sama_7": {
    en: "&copy; 2026 Indian Knowledge Systems. All rights reserved.",
    hi: "&copy; 2026 भारतीय ज्ञान प्रणाली। सर्वाधिकार सुरक्षित।"
  }
};
