window.IKS_TRANSLATIONS = {
  "yajur_1": {
    en: "The Yajurveda is the Veda of prose mantras and ritual actions. If the Rigveda provides the words of praise and the Samaveda provides the melody, the Yajurveda provides the procedural manual for the ancient rituals (Yajnas). Composed roughly between 1200 and 1000 BCE, it served as a practical guidebook for the Adhvaryu priests who performed the physical actions of the sacrifices, detailing exactly how the altars were to be constructed, how the fires were to be lit, and what offerings were to be made.",
    hi: "यजुर्वेद गद्य मंत्रों और अनुष्ठान कार्यों का वेद है। यदि ऋग्वेद स्तुति के शब्द प्रदान करता है और सामवेद धुन प्रदान करता है, तो यजुर्वेद प्राचीन अनुष्ठानों (यज्ञों) के लिए प्रक्रियात्मक मैनुअल प्रदान करता है। मोटे तौर पर 1200 से 1000 ईसा पूर्व के बीच रचित, यह अध्वर्यु पुजारियों के लिए एक व्यावहारिक मार्गदर्शिका के रूप में कार्य करता था जो यज्ञों के भौतिक कार्य करते थे, यह विस्तार से बताते थे कि वेदियों का निर्माण कैसे किया जाना था, आग कैसे जलाई जानी थी, और क्या आहुतियां दी जानी थीं।"
  },
  "yajur_2": {
    en: "The text exists in two major recensions: the Krishna (Black) Yajurveda and the Shukla (White) Yajurveda. The Krishna Yajurveda is the older of the two and presents a continuous, undifferentiated text where the mantras (verses) and the Brahmanas (prose explanations) are blended together. The Shukla Yajurveda, attributed to the sage Yajnavalkya, separates the mantras from the explanatory text, providing a clearer, more organized structure. This division highlights a crucial moment in Indian intellectual history — the recognition of the need for systematic organization and pedagogical clarity in transmitting complex knowledge.",
    hi: "यह ग्रंथ दो प्रमुख शाखाओं में मौजूद है: कृष्ण (काला) यजुर्वेद और शुक्ल (सफेद) यजुर्वेद। कृष्ण यजुर्वेद दोनों में से पुराना है और एक सतत, अविभाजित पाठ प्रस्तुत करता है जहाँ मंत्र (श्लोक) और ब्राह्मण (गद्य स्पष्टीकरण) एक साथ मिश्रित होते हैं। महर्षि याज्ञवल्क्य द्वारा रचित शुक्ल यजुर्वेद, व्याख्यात्मक पाठ से मंत्रों को अलग करता है, जो एक स्पष्ट, अधिक सुव्यवस्थित संरचना प्रदान करता है। यह विभाजन भारतीय बौद्धिक इतिहास में एक महत्वपूर्ण क्षण को उजागर करता है — जटिल ज्ञान को प्रसारित करने में व्यवस्थित संगठन और शैक्षणिक स्पष्टता की आवश्यकता की मान्यता।"
  },
  "yajur_3": {
    en: "At the heart of the Yajurveda is the concept of Yajna (sacrifice). However, Yajna was not merely a religious ritual; it was viewed as a microcosmic recreation of the macrocosmic order. The construction of the fire altar required profound geometrical and mathematical precision, laying the foundation for Sulba Sutras (ancient Indian geometry). The timing of the rituals required precise astronomical calculations, advancing the science of Jyotisha (astronomy). Yajna was the organizing principle of early Vedic society, connecting the individual, the community, nature, and the divine in a cycle of mutual dependence and sustenance.",
    hi: "यजुर्वेद के केंद्र में यज्ञ (बलिदान) की अवधारणा है। हालाँकि, यज्ञ केवल एक धार्मिक अनुष्ठान नहीं था; इसे व्यापक ब्रह्मांडीय व्यवस्था के एक सूक्ष्म मनोरंजन के रूप में देखा गया था। अग्नि वेदी के निर्माण के लिए गहन ज्यामितीय और गणितीय सटीकता की आवश्यकता थी, जिसने शुल्ब सूत्रों (प्राचीन भारतीय ज्यामिति) की नींव रखी। अनुष्ठानों के समय के लिए सटीक खगोलीय गणनाओं की आवश्यकता थी, जिससे ज्योतिष (खगोल विज्ञान) के विज्ञान को आगे बढ़ाया गया। यज्ञ प्रारंभिक वैदिक समाज का आयोजन सिद्धांत था, जो व्यक्ति, समुदाय, प्रकृति और परमात्मा को आपसी निर्भरता और जीविका के चक्र में जोड़ता था।"
  },
  "yajur_4": {
    en: "The Yajurveda contains some of the most profound philosophical concepts in Indian thought, particularly within its final chapter — the Isha Upanishad. The Isha Upanishad famously declares: \"Isha vasyam idam sarvam\" — \"All this, whatever moves in this moving world, is enveloped by God.\" It teaches the harmonious integration of action (Karma) and knowledge (Jnana), instructing humans to perform their duties selflessly while recognizing the divine presence in all things. It warns against both the path of blind action without knowledge and the path of abstract knowledge without action.",
    hi: "यजुर्वेद में भारतीय विचार की कुछ सबसे गहन दार्शनिक अवधारणाएँ शामिल हैं, विशेष रूप से इसके अंतिम अध्याय — ईशावास्योपनिषद के भीतर। ईशावास्योपनिषद प्रसिद्ध रूप से घोषणा करता है: 'ईशावास्यमिदं सर्वं' — 'यह सब, जो कुछ भी इस चलती दुनिया में चलता है, वह ईश्वर से आच्छादित है।' यह कर्म (क्रिया) और ज्ञान (ज्ञान) के सामंजस्यपूर्ण एकीकरण को सिखाता है, मनुष्यों को सभी चीजों में दिव्य उपस्थिति को पहचानते हुए निस्वार्थ रूप से अपने कर्तव्यों का पालन करने का निर्देश देता है। यह ज्ञान के बिना अंधे कर्म के मार्ग और कर्म के बिना अमूर्त ज्ञान के मार्ग दोनों के खिलाफ चेतावनी देता है।"
  },
  "yajur_5": {
    en: "The environmental ethics of the Yajurveda are highly relevant today. It contains prayers not just for human prosperity, but for the well-being of the entire ecosystem: \"May there be peace in the heavens, peace in the atmosphere, peace on earth, peace in the waters, peace in the medicinal plants, peace in the forests...\" This holistic vision, which sees human flourishing as inextricably linked to environmental health, provides a powerful philosophical basis for modern ecological conservation.",
    hi: "यजुर्वेद की पर्यावरणीय नैतिकता आज अत्यधिक प्रासंगिक है। इसमें न केवल मानव समृद्धि के लिए प्रार्थनाएँ शामिल हैं, बल्कि पूरे पारिस्थितिकी तंत्र की भलाई के लिए भी हैं: 'स्वर्ग में शांति हो, वायुमंडल में शांति हो, पृथ्वी पर शांति हो, पानी में शांति हो, औषधीय पौधों में शांति हो, जंगलों में शांति हो...' यह समग्र दृष्टि, जो मानव विकास को पर्यावरणीय स्वास्थ्य से अटूट रूप से जुड़ा हुआ देखती है, आधुनिक पारिस्थितिक संरक्षण के लिए एक शक्तिशाली दार्शनिक आधार प्रदान करती है।"
  },
  "yajur_6": {
    en: "&copy; 2026 Indian Knowledge Systems. All rights reserved.",
    hi: "&copy; 2026 भारतीय ज्ञान प्रणाली। सर्वाधिकार सुरक्षित।"
  }
};
